from EmotionClassifier import EmotionClassifier
import spotipy
import re
from spotipy.oauth2 import SpotifyClientCredentials
import random
emotion_to_genre = {
            'admiration': ['inspirational', 'pop'],
            'amusement': ['feel-good', 'indie', 'dance'],
            'anger': ['rock', 'metal', 'punk'],
            'annoyance': ['grunge', 'alternative'],
            'approval': ['chill', 'lofi'],
            'caring': ['acoustic', 'folk'],
            'confusion': ['ambient', 'electronic'],
            'curiosity': ['indie', 'alternative', 'electronic'],
            'desire': ['rnb', 'soul', 'romance'],
            'disappointment': ['sad', 'acoustic'],
            'disapproval': ['emo', 'grunge'],
            'disgust': ['industrial', 'darkwave'],
            'embarrassment': ['jazz', 'soft pop'],
            'excitement': ['edm', 'party', 'dance'],
            'fear': ['cinematic', 'ambient'],
            'gratitude': ['happy', 'acoustic', 'pop'],
            'grief': ['piano', 'sad'],
            'joy': ['pop', 'dance', 'happy'],
            'love': ['romantic', 'rnb', 'soul'],
            'nervousness': ['lofi', 'ambient'],
            'optimism': ['indie', 'happy', 'pop'],
            'pride': ['hip-hop', 'rap'],
            'realization': ['indie', 'chill'],
            'relief': ['chill', 'indie', 'lofi'],
            'remorse': ['blues', 'sad'],
            'sadness': ['sad', 'acoustic', 'piano'],
            'surprise': ['electronic', 'pop'],
            'neutral': ['lofi', 'indie', 'pop']
        }
artist_patterns = [
            r'by\s+([a-zA-Z][a-zA-Z0-9\s&.\'-]{1,30}?)(?=\s*(?:and|,|\.|!|\?|$))',
            r'from\s+([a-zA-Z][a-zA-Z0-9\s&.\'-]{1,30}?)(?=\s*(?:and|,|\.|!|\?|$))',
            r"([a-zA-Z][a-zA-Z0-9\s&.\'-]{1,30}?)'s\s+(?:music|song|track|album)",
            r'artist\s+([a-zA-Z][a-zA-Z0-9\s&.\'-]{1,30}?)(?=\s*(?:and|,|\.|!|\?|$))',
            r'listen(?:ing)?\s+to\s+([a-zA-Z][a-zA-Z0-9\s&.\'-]{1,30}?)(?=\s*(?:and|,|\.|!|\?|$))',
            r'song\s+by\s+([a-zA-Z][a-zA-Z0-9\s&.\'-]{1,30}?)(?=\s*(?:and|,|\.|!|\?|$))',
            r'recommend.*?by\s+([a-zA-Z][a-zA-Z0-9\s&.\'-]{1,30}?)(?=\s*(?:and|,|\.|!|\?|$))',
        ]

emotion_keywords = {
            'sadness': ['sad', 'tear', 'tears', 'cry', 'crying', 'alone', 'lonely', 'lost', 'hurt', 'hurting',
                        'pain', 'painful', 'sorry', 'goodbye', 'bye', 'miss', 'missing', 'empty', 'blue', 'dark',
                        'darkness', 'rain', 'raining', 'cold', 'break', 'broken', 'end', 'ending', 'last', 'never',
                        'forget', 'remember', 'remembering', 'haunt', 'haunted', 'ghost', 'night', 'midnight',
                        'death', 'die', 'dying', 'grave', 'mourning', 'mourn', 'sorrow', 'regret', 'shame',
                        'melancholy', 'down', 'gray', 'grey', 'winter', 'fall', 'falling', 'fade', 'fading'],
            'joy': ['happy', 'happiness', 'joy', 'joyful', 'smile', 'smiling', 'celebrate', 'celebration',
                    'celebrating', 'sunshine', 'sun', 'sunny', 'love', 'loving', 'beautiful', 'wonderful',
                    'bright', 'dance', 'dancing', 'party', 'partying', 'fun', 'laugh', 'laughing', 'laughter',
                    'sweet', 'shine', 'shining', 'gold', 'golden', 'light', 'up', 'high', 'summer', 'good'],
            'anger': ['angry', 'anger', 'rage', 'raging', 'hate', 'hatred', 'hating', 'fight', 'fighting',
                      'scream', 'screaming', 'mad', 'fury', 'furious', 'war', 'revenge', 'destroy', 'destruction',
                      'kill', 'killing', 'blood', 'bloody', 'fire', 'burn', 'burning', 'hell'],
            'love': ['love', 'loving', 'loved', 'lover', 'heart', 'hearts', 'kiss', 'kissing', 'kisses',
                     'romance', 'romantic', 'together', 'forever', 'darling', 'baby', 'sweet', 'sweetheart',
                     'mine', 'yours', 'beloved', 'adore', 'passion', 'desire'],
            'excitement': ['party', 'parties', 'dance', 'dancing', 'wild', 'night', 'nights', 'tonight',
                           'crazy', 'fun', 'shake', 'shaking', 'move', 'moving', 'jump', 'jumping', 'energy',
                           'electric', 'fire', 'alive', 'ready', 'go', 'yeah', 'woah'],
            'fear': ['afraid', 'scared', 'fear', 'fearful', 'nightmare', 'nightmares', 'dark', 'darkness',
                     'haunt', 'haunted', 'shadow', 'shadows', 'monster', 'monsters', 'terror', 'panic',
                     'anxiety', 'anxious', 'worry', 'worried'],
            'grief': ['loss', 'lost', 'lose', 'gone', 'going', 'never', 'end', 'ending', 'last', 'final',
                      'memory', 'memories', 'remember', 'remembering', 'funeral', 'grave', 'dead', 'death',
                      'dying', 'die', 'left', 'leaving', 'goodbye'],
            'gratitude': ['thank', 'thanks', 'grateful', 'gratitude', 'bless', 'blessed', 'blessing',
                          'blessings', 'appreciate', 'appreciation', 'grace'],
            'disappointment': ['disappoint', 'disappointed', 'disappointing', 'let down', 'failed', 'failure',
                               'failing', 'broken', 'wrong', 'mistake', 'mistakes', 'regret', 'regretful'],
            'confusion': ['confuse', 'confused', 'confusing', 'lost', 'wonder', 'wondering', 'question',
                          'questions', 'questioning', 'why', 'don\'t know', 'unknown', 'mystery', 'mysterious',
                          'strange', 'weird', 'maze'],
            'relief': ['relief', 'relieved', 'free', 'freedom', 'finally', 'over', 'breathe', 'breathing',
                       'breath', 'calm', 'calming', 'peace', 'peaceful', 'easy', 'lighter', 'relax'],
            'optimism': ['hope', 'hopeful', 'hoping', 'dream', 'dreaming', 'dreams', 'dreamer', 'believe',
                         'believing', 'tomorrow', 'future', 'shine', 'shining', 'rise', 'rising', 'new',
                         'begin', 'beginning', 'start', 'starting', 'faith', 'trust', 'better', 'up'],
            'neutral': [],
        }

